"""Tabla de reciclaje

Revision ID: 3a1f4a29e763
Revises: 9e63422271bf
Create Date: 2024-07-25 13:30:22.378216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1f4a29e763'
down_revision = '9e63422271bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciclaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vidrio', sa.Boolean(), nullable=True),
    sa.Column('metal', sa.Boolean(), nullable=True),
    sa.Column('plastico', sa.Boolean(), nullable=True),
    sa.Column('carton', sa.Boolean(), nullable=True),
    sa.Column('usuario_de_reciclaje', sa.Integer(), nullable=False),
    sa.Column('usuario_recolector_en_camino', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_de_reciclaje'], ['Usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_recolector_en_camino'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reciclaje')
    # ### end Alembic commands ###
