"""Mapa de reciclaje coordenadas null true

Revision ID: 50c2f4162d0e
Revises: 6896d4551aee
Create Date: 2024-07-26 11:09:58.482524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c2f4162d0e'
down_revision = '6896d4551aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_de_reciclaje', schema=None) as batch_op:
        batch_op.alter_column('coordenada_x',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('coordenada_y',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_de_reciclaje', schema=None) as batch_op:
        batch_op.alter_column('coordenada_y',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('coordenada_x',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
