"""Mapa de reciclaje

Revision ID: 6896d4551aee
Revises: 3a1f4a29e763
Create Date: 2024-07-26 10:55:43.233149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6896d4551aee'
down_revision = '3a1f4a29e763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapa_de_reciclaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reciclaje_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en camino', 'recogido'), nullable=True),
    sa.Column('coordenada_x', sa.Float(), nullable=False),
    sa.Column('coordenada_y', sa.Float(), nullable=False),
    sa.Column('recolector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reciclaje_id'], ['reciclaje.id'], ),
    sa.ForeignKeyConstraint(['recolector_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapa_de_reciclaje')
    # ### end Alembic commands ###
