"""Add lastname and address columns to Users table

Revision ID: 9844c78e331a
Revises: 546d25f141a4
Create Date: 2024-07-23 01:44:36.193473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9844c78e331a'
down_revision = '546d25f141a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
