"""Add lastname and address columns to Users table

Revision ID: 9e63422271bf
Revises: 9844c78e331a
Create Date: 2024-07-23 01:47:01.871929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e63422271bf'
down_revision = '9844c78e331a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
